return
{
	equipment =
	{
		{ type = "energy-shield-equipment", name = "yi_equip_shield_a", chassis = { "player" }, minimum_tier = 3, },
		{ type = "energy-shield-equipment", name = "yi_equip_shield_b", chassis = { "player" }, minimum_tier = 4, },
		{ type = "battery-equipment", name = "yi_equip_battery_a", chassis = { "player" }, minimum_tier = 3, },
		{ type = "generator-equipment", name = "yi_equip_generator_a", chassis = { "player" }, minimum_tier = 4, },
		{ type = "movement-bonus-equipment", name = "yi_equip_legs_a", chassis = { "player" }, engines = { "powered" } },
		{ type = "roboport-equipment", name = "yi_equip_roboport", chassis = { "player" }, minimum_tier = 3, },
		{ type = "active-defense-equipment", name = "yi_pld_equipment", chassis = { "player" }, minimum_tier = 3, },
	},
	armors =
	{
		{ name = "yi_armor_gray", role = "cargo", tier = 3},
		{ name = "yi_armor_red", role = "support", tier = 4},
		{ name = "yi_armor_gold", role = "support", tier = 5},
		{ name = "yi_walker_a", role = "combat", tier = 5},
		{ name = "yi_walker_c", role = "combat", tier = 6},
	},
	vehicles =
	{
		{ type = "cargo-wagon", name = "yir_wagon_caboose_cr", engine = "unpowered", role = "support", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4a_container_cr", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4a_clean_cr", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_es44cr", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_emdf7a_cr", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_emdf7a_mn", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_emdf7b_cr", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_emdf7b_mn", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_corn_blue", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_corn_green", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_trans", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_closed", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_hopper_yellow", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_2acw_wood", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_coal", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_copper", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_iron", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_stone", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_2acw_3blocks", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_zement_gray", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_wagon_zement_white", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_closed", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_coal", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_copper", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_iron", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_vc", engine = "unpowered", role = "cargo", chassis = "train", tier = 3 },
		{ type = "cargo-wagon", name = "yir_4acw_wood", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_mun", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_tf", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_gold", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_stone", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_grey", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_oceanblue", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_4acw_purple", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_fw4_vc", engine = "unpowered", role = "cargo", chassis = "train", tier = 3 },
		{ type = "fluid-wagon", name = "y_wagon_tank_blue", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "fluid-wagon", name = "y_wagon_tank_orange", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "fluid-wagon", name = "y_wagon_tank_orange", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "fluid-wagon", name = "yir_fw4a_tank_oil", engine = "unpowered", role = "cargo", chassis = "train", tier = 3 },
		{ type = "fluid-wagon", name = "y_wagon_tank_blue", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "fluid-wagon", name = "y_wagon_tank_fm2", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "fluid-wagon", name = "y_wagon_tank_fm1", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_loco_del_mk1400", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_wagon_tender_black", engine = "powered", role = "support", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_wagon_tender_green", engine = "powered", role = "support", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_loco_fut_red", engine = "powered", role = "cargo", chassis = "train", tier = 4 },
		{ type = "locomotive", name = "yir_loco_del_KR", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_ses_std", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_loco_sel_blue", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_emd3000_white", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_desw", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_desw_orange", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_desw_blue", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_emd1500black", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_emd1500blue", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_emd1500blue_v2", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_emd1500black_v2", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_diesel_620", engine = "powered", role = "cargo", chassis = "train", tier = 3 },
		{ type = "locomotive", name = "y_loco_ses_red", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_loco_fesw_op", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_fs_steam_green", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "y_loco_steam_wt450", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_loco_del_bluegray", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_empty_4a", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_flourit_4a", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_trans_4a", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_uran_4a", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_upempty", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_flourit", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_upclosed", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_uranite", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_4a_cellsu", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_4a_urana", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_atom_header", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_atom_mitte", engine = "powered", role = "support", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_cargo_green", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_cw_cargo_blue", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_kisten", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_stuff1", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "y_3acw_T10K", engine = "unpowered", role = "cargo", chassis = "train", tier = 4 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_kiste1", engine = "unpowered", role = "cargo", chassis = "train", tier = 3 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_yigreen", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_gears", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_yiblue", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_energy", engine = "unpowered", role = "cargo", chassis = "train", tier = 4 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_eb1", engine = "unpowered", role = "cargo", chassis = "train", tier = 4 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_ziegelrot", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "z_yira_6a_maai1", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_steel", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "z_yira_4a_cw_ziegelgrau", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "cargo-wagon", name = "yir_us_cargo", engine = "unpowered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_lsw_r790orange", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_lsw_r790red", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_lsw_840green", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_ns2200gg", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_ns2200wr", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_kr_green", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_loco_steam_wt580of", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_mre044", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
		{ type = "locomotive", name = "yir_usl", engine = "powered", role = "cargo", chassis = "train", tier = 2 },
	}
}