-- Yuoki has a productivity recipe list... but applies it in the data phase, so yuoki's modules (from yuoki engines, which loads after yuoki itself) don't exist yet and thus aren't updated
-- so, we're stealing that for here and re-running it to get other modules

return
{
	recipes =
	{
		{ name = "y_slag_brick_burn_recipe" },
		{ name = "y_slag_brick_recipe" },
		{ name = "y_slag_granulate_recipe" },
		{ name = "y_hps_steel_recipe" },
		{ name = "y_hps_purecopper_recipe" },
		{ name = "y_hps_pureiron_recipe" },
		{ name = "y-basic-st2-mf-recipe" },
		{ name = "y-chip2-recipe" },
		{ name = "yi_magnetron_recipe" },
		{ name = "y-battery-singleuse1-recipe" },
		{ name = "y-battery-singleuse2-recipe" },
		{ name = "y-battery-single-use3-recipe" },
		{ name = "y_blocked_capa_recipe" },
		{ name = "y-crystal-cnd-recipe" },
		{ name = "y-quantrinum-recipe" },
		{ name = "y-fuel-reactor-recipe" },
		{ name = "y-infused-mud-recipe" },
		{ name = "y-infused-uca2-recipe" },
		{ name = "y_mud2solidfuel_recipe" },
		{ name = "y_mixedfuel2rocketfuel_recipe" },
		{ name = "y-mixfuel-load-recipe" },
		{ name = "y-wooden-brikett-packed-recipe" },
		{ name = "y-pure-copper-recipe" },
		{ name = "y-pure-iron-recipe" },
		{ name = "y-refined-copper" },
		{ name = "y-refined-iron" },
		{ name = "y-wash-dirt-recipe" },
		{ name = "y-mixing-rich-recipe" },
		{ name = "y-press-richdust-recipe" },
		{ name = "y-orange-stuff_recipe" },
		{ name = "y-smelt-crush-res1-recipe" },
		{ name = "y-smelt-crush-res2-recipe" },
		{ name = "y_quantrinum_infusion_recipe" },
		{ name = "y_mox1fuel_recipe" },
		{ name = "y_mox1mixed_recipe" },
		{ name = "y_mox2fuel_recipe" },
		{ name = "y_mox2mixed_recipe" },
		{ name = "y_mox2fuelsplit_recipe" },
		{ name = "y_structure_element_recipe" },
		{ name = "y-bluegear-recipe" },
		{ name = "y_structure_vessel_recipe" },
		{ name = "y-basic-st1-mf-recipe" },
		{ name = "y_chip_plate_recipe" },
		{ name = "y_dotzetron_recipe" },
		{ name = "y_structure_electric_recipe" },
		{ name = "y-heat-pipe-recipe" },
		{ name = "y-heat-pipe-recipe" },
		{ name = "y-conductive-coil-1-recipe" },
		{ name = "y-conductive-wire-1_recipe" },
		{ name = "y-crush-unicomp-raw-recipe" },
		{ name = "y-crush-fuel-raw-recipe" },
		{ name = "y_slag_granulate_recipe" },
		{ name = "y_steinmehl_recipe" },
		{ name = "y-coaldust-recipe" },
		{ name = "y_granulate_wood_recipe" },
		{ name = "y-unicomp-raw-recipe" },
		{ name = "y-raw-fuelnium-recipe" },
		{ name = "y-bullet-case-recipe" },
		{ name = "y_ammo_case_recipe" },
		{ name = "yi_graphite_recipe" },
		{ name = "y_data_crystal_recipe" },
		{ name = "y_gauge_analog_recipe" },

		-- recipes that yuoki didn't include but probably should have
		{ name = "y-chip1-recipe" },

		-- our recipes
		{ name = "angels-plate-durotal" },
		{ name = "angels-refined-durotal" },
		{ name = "angels-plate-nuatreel" },
		{ name = "angels-refined-nuatreel" },

		{ name = "advanced-circuit-y" },
		{ name = "processing-unit-y" },
		{ name = "advanced-processing-unit-y" },
	},
	categories =
	{
		{ name = "yrcat-farm", types = { "agricultural" }},
		{ name = "yrcat-fish", types = { "agricultural" }},
		{ name = "yrcat_meat", types = { "agricultural" }},
	},
}