-- update refining recipes to make the ratios nicer
guftlib.recipe.energy_set("clowns-ore1-chunk", 1)
guftlib.recipe.energy_set("clowns-ore2-chunk", 1)
guftlib.recipe.energy_set("clowns-ore3-chunk", 1)
guftlib.recipe.energy_set("clowns-ore4-chunk", 1)
guftlib.recipe.energy_set("clowns-ore5-chunk", 1)
guftlib.recipe.energy_set("clowns-ore6-chunk", 1)
guftlib.recipe.energy_set("clowns-ore7-chunk", 1)
guftlib.recipe.energy_set("clowns-ore8-chunk", 1)
guftlib.recipe.energy_set("clowns-ore9-chunk", 1)

guftlib.recipe.energy_set("clowns-ore1-chunk-processing", 1)
guftlib.recipe.energy_set("clowns-ore2-chunk-processing", 1)
guftlib.recipe.energy_set("clowns-ore3-chunk-processing", 1)
guftlib.recipe.energy_set("clowns-ore4-chunk-processing", 1)
guftlib.recipe.energy_set("clowns-ore5-chunk-processing", 1)
guftlib.recipe.energy_set("clowns-ore6-chunk-processing", 1)
guftlib.recipe.energy_set("clowns-ore7-chunk-processing", 1)
guftlib.recipe.energy_set("clowns-ore8-chunk-processing", 1)
guftlib.recipe.energy_set("clowns-ore9-chunk-processing", 1)

guftlib.recipe.input_set_quantity("clowns-ore1-chunk-processing", "clowns-ore1-chunk", 6)
guftlib.recipe.input_set_quantity("clowns-ore2-chunk-processing", "clowns-ore2-chunk", 6)
guftlib.recipe.input_set_quantity("clowns-ore3-chunk-processing", "clowns-ore3-chunk", 6)
guftlib.recipe.input_set_quantity("clowns-ore4-chunk-processing", "clowns-ore4-chunk", 6)
guftlib.recipe.input_set_quantity("clowns-ore5-chunk-processing", "clowns-ore5-chunk", 6)
guftlib.recipe.input_set_quantity("clowns-ore6-chunk-processing", "clowns-ore6-chunk", 6)
guftlib.recipe.input_set_quantity("clowns-ore7-chunk-processing", "clowns-ore7-chunk", 6)
guftlib.recipe.input_set_quantity("clowns-ore8-chunk-processing", "clowns-ore8-chunk", 6)
guftlib.recipe.input_set_quantity("clowns-ore9-chunk-processing", "clowns-ore9-chunk", 6)

guftlib.recipe.energy_set("clowns-ore1-crystal-processing", 1)
guftlib.recipe.energy_set("clowns-ore2-crystal-processing", 1)
guftlib.recipe.energy_set("clowns-ore3-crystal-processing", 1)
guftlib.recipe.energy_set("clowns-ore4-crystal-processing", 1)
guftlib.recipe.energy_set("clowns-ore5-crystal-processing", 1)
guftlib.recipe.energy_set("clowns-ore6-crystal-processing", 1)
guftlib.recipe.energy_set("clowns-ore7-crystal-processing", 1)
guftlib.recipe.energy_set("clowns-ore8-crystal-processing", 1)
guftlib.recipe.energy_set("clowns-ore9-crystal-processing", 1)

guftlib.recipe.energy_set("clowns-ore1-crystal", 1)
guftlib.recipe.energy_set("clowns-ore2-crystal", 1)
guftlib.recipe.energy_set("clowns-ore3-crystal", 1)
guftlib.recipe.energy_set("clowns-ore4-crystal", 1)
guftlib.recipe.energy_set("clowns-ore5-crystal", 1)
guftlib.recipe.energy_set("clowns-ore6-crystal", 1)
guftlib.recipe.energy_set("clowns-ore7-crystal", 1)
guftlib.recipe.energy_set("clowns-ore8-crystal", 1)
guftlib.recipe.energy_set("clowns-ore9-crystal", 1)

guftlib.recipe.energy_set("clowns-ore1-pure-processing", 1)
guftlib.recipe.energy_set("clowns-ore2-pure-processing", 1)
guftlib.recipe.energy_set("clowns-ore3-pure-processing", 1)
guftlib.recipe.energy_set("clowns-ore4-pure-processing", 1)
guftlib.recipe.energy_set("clowns-ore5-pure-processing", 1)
guftlib.recipe.energy_set("clowns-ore6-pure-processing", 1)
guftlib.recipe.energy_set("clowns-ore7-pure-processing", 1)
guftlib.recipe.energy_set("clowns-ore8-pure-processing", 1)
guftlib.recipe.energy_set("clowns-ore9-pure-processing", 1)

guftlib.recipe.input_set_quantity("clowns-ore1-pure-processing", "clowns-ore1-pure", 10)
guftlib.recipe.input_set_quantity("clowns-ore2-pure-processing", "clowns-ore2-pure", 10)
guftlib.recipe.input_set_quantity("clowns-ore3-pure-processing", "clowns-ore3-pure", 10)
guftlib.recipe.input_set_quantity("clowns-ore4-pure-processing", "clowns-ore4-pure", 10)
guftlib.recipe.input_set_quantity("clowns-ore5-pure-processing", "clowns-ore5-pure", 10)
guftlib.recipe.input_set_quantity("clowns-ore6-pure-processing", "clowns-ore6-pure", 10)
guftlib.recipe.input_set_quantity("clowns-ore7-pure-processing", "clowns-ore7-pure", 10)
guftlib.recipe.input_set_quantity("clowns-ore8-pure-processing", "clowns-ore8-pure", 10)
guftlib.recipe.input_set_quantity("clowns-ore9-pure-processing", "clowns-ore9-pure", 10)